spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bank_rest
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
#security:
#  jwt:
#    token:
#      secret-key: ${JWT_SECRET}